name: Flask App Tests

on:
  pull_requests:
    branches:
      - main
# Run the workflow specified below when pull request on main branch

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/
      
    strategy:
      matrix:
        python-version: [3.11]
    
    env:
      MODE: 'dev'

    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
      
      - name: Test app code
        run: python ./main_test.py


    